### ISSUE TITLE
Task - Create next iteration of homepage wireframe

### ISSUE THREAD

**Issue by yehk** [18F/data-act-usaspending#29] opened 2015-07-09 21:54 UTC

**Comment by cedwards-reisys** [comment] 2015-07-09 22:40
Is this a duplicate of #3?

**Comment by marco-poplicus** [comment] 2015-07-22 18:11
![wireframe_homepage_00-01](https://cloud.githubusercontent.com/assets/5605410/8833169/780f47e4-307b-11e5-9710-b275fe653712.png)
![wireframe_homepage_01-01](https://cloud.githubusercontent.com/assets/5605410/8833168/780f2dfe-307b-11e5-869d-8193413467b2.png)
![wireframe_homepage_02-01](https://cloud.githubusercontent.com/assets/5605410/8833166/780db334-307b-11e5-8416-94ccddbda88d.png)
![wireframe_homepage_03-01](https://cloud.githubusercontent.com/assets/5605410/8833167/780de6e2-307b-11e5-8e38-7a74615a80a6.png)
![wireframe_homepage_04-01](https://cloud.githubusercontent.com/assets/5605410/8833170/780fe064-307b-11e5-800a-7a8832a45580.png)
![wireframe_homepage_05-01](https://cloud.githubusercontent.com/assets/5605410/8833171/7816260e-307b-11e5-8239-105f7166c2e5.png)
![wireframe_homepage_06-01](https://cloud.githubusercontent.com/assets/5605410/8833176/7839d4a0-307b-11e5-914a-9e4792543666.png)
![wireframe_homepage_07-01](https://cloud.githubusercontent.com/assets/5605410/8833173/782ab60a-307b-11e5-8536-c4198bced8c6.png)
![wireframe_homepage_08-01](https://cloud.githubusercontent.com/assets/5605410/8833172/782a453a-307b-11e5-979c-43e4fd00eca0.png)
![wireframe_homepage_09-01](https://cloud.githubusercontent.com/assets/5605410/8833175/782d7ffc-307b-11e5-877d-dcfd63101247.png)
![wireframe_homepage_10-01](https://cloud.githubusercontent.com/assets/5605410/8833177/783f10fa-307b-11e5-8e57-da9317c639fb.png)
![wireframe_homepage_11-01](https://cloud.githubusercontent.com/assets/5605410/8833174/782d5c98-307b-11e5-97f2-3ff0c07d24ab.png)

**Comment by marco-poplicus** [comment] 2015-07-27 15:05
![wireframe_homepage_00-01](https://cloud.githubusercontent.com/assets/5605410/8909436/5a537ff4-344f-11e5-9e9d-cabe56d711f7.png)
![wireframe_homepage_01-01](https://cloud.githubusercontent.com/assets/5605410/8909437/5a64124c-344f-11e5-9cb1-471eb2c2c47f.png)
![wireframe_homepage_02-01](https://cloud.githubusercontent.com/assets/5605410/8909438/5a680de8-344f-11e5-9c15-9c4b7a01eb7d.png)
![wireframe_homepage_03-01](https://cloud.githubusercontent.com/assets/5605410/8909439/5a6d1950-344f-11e5-9d48-c35e8a5d0f5d.png)
![wireframe_homepage_04-01](https://cloud.githubusercontent.com/assets/5605410/8909441/5a75c8b6-344f-11e5-8cbc-23afc16698ec.png)
![wireframe_homepage_05-01](https://cloud.githubusercontent.com/assets/5605410/8909442/5a7b9c78-344f-11e5-814f-9fa260f49079.png)
![wireframe_homepage_06-01](https://cloud.githubusercontent.com/assets/5605410/8909440/5a7305f4-344f-11e5-87de-410301142d61.png)
![wireframe_homepage_07-01](https://cloud.githubusercontent.com/assets/5605410/8909446/5a7e125a-344f-11e5-990e-de7882947b31.png)
![wireframe_homepage_08-01](https://cloud.githubusercontent.com/assets/5605410/8909443/5a80743c-344f-11e5-9c49-c9bb26cd3316.png)
![wireframe_homepage_09-01](https://cloud.githubusercontent.com/assets/5605410/8909447/5a8d5a3a-344f-11e5-9b3b-9c181923a0e2.png)
![wireframe_homepage_10-01](https://cloud.githubusercontent.com/assets/5605410/8909445/5a84b8ee-344f-11e5-8400-86b313a6a5ab.png)
![wireframe_homepage_11-01](https://cloud.githubusercontent.com/assets/5605410/8909444/5a8448be-344f-11e5-86ec-f282280ec01b.png)
![wireframe_homepage_12-01](https://cloud.githubusercontent.com/assets/5605410/8909448/5a8ef778-344f-11e5-8dd0-9ad678e035cd.png)
![wireframe_homepage_13-01](https://cloud.githubusercontent.com/assets/5605410/8909449/5a983bd0-344f-11e5-9e52-06d8f67e7a06.png)

**Comment by AGuyNamedMarco** [comment] 2015-07-29 18:56
![wireframe_homepage_01-01](https://cloud.githubusercontent.com/assets/5605410/8966927/0369c374-3602-11e5-888d-5dc1be411b4d.png)
![wireframe_homepage_02-01](https://cloud.githubusercontent.com/assets/5605410/8966926/03686d80-3602-11e5-8429-4c7406dd773d.png)
![wireframe_homepage_03-01](https://cloud.githubusercontent.com/assets/5605410/8966928/036c5882-3602-11e5-8e86-57b3bec3dbfa.png)
![wireframe_homepage_04-01](https://cloud.githubusercontent.com/assets/5605410/8966930/036dbac4-3602-11e5-90c9-0174d9acf0ca.png)
![wireframe_homepage_05-01](https://cloud.githubusercontent.com/assets/5605410/8966925/036847c4-3602-11e5-8926-7fd47982e8e8.png)
![wireframe_homepage_06-01](https://cloud.githubusercontent.com/assets/5605410/8966929/036d0f98-3602-11e5-984a-9c6bb26e57c9.png)
![wireframe_homepage_07-01](https://cloud.githubusercontent.com/assets/5605410/8966931/03713dde-3602-11e5-8473-f262cd5689fc.png)
![wireframe_homepage_08-01](https://cloud.githubusercontent.com/assets/5605410/8966932/0372660a-3602-11e5-83a4-cea77fe4274d.png)

**Comment by yehk** [comment] 2015-09-22 20:32
Reopen to discuss wireframes.

**Closed as completed** 2015-09-24 11:03 UTC
